### ISSUE TITLE
Does not work when running in terminal?

### ISSUE THREAD

**Issue by jbmulligan** [L-TChen/auto-dark-mode.vim#2]
I just installed this, and have it working nicely in GUI mode (which I had never used before), but I am wondering whether there is any way to get it to work when running in the terminal (mvim -v)?  I guess the root of the problem is that the OS delivers the appearance change events to the app, which in the non-GUI case is Terminal.app, not macvim?  If that is correct, is there no way to have the event forwarded, or would that require hacking Terminal?

**Comment by L-TChen** [comment]
The appearance change events are sent to GUIs only (to be precise, an instance of [NSAppearance](https://developer.apple.com/documentation/appkit/nsappearance)) and bypassed to the Vim core so that the core can emit the corresponding event. `Terminal.app` does not send the event to Vim, so I don't think Vim can change its appearance instantly. I guess there is a way to do it in `iTerm2`, but I don't know.

Another possible working approach is to monitor the event via Apple Script or something like that, but it takes some time to see change depending on the time interval.

**Comment by huyz** [comment]
I wonder if https://github.com/cormacrelf/dark-notify/ could be useful
